#pragma once

#include <string>

std::string examplePriceHistory =
    R"({
  "symbol": "AAPL",
  "empty": false,
  "previousClose": 174.56,
  "previousCloseDate": 1639029600000,
  "candles": [
    {
      "open": 175.01,
      "high": 175.15,
      "low": 175.01,
      "close": 175.04,
      "volume": 10719,
      "datetime": 1639137600000
    },
    {
      "open": 175.08,
      "high": 175.09,
      "low": 175.05,
      "close": 175.05,
      "volume": 500,
      "datetime": 1639137660000
    },
    {
      "open": 176.22,
      "high": 176.27,
      "low": 176.22,
      "close": 176.25,
      "volume": 3395,
      "datetime": 1640307300000
    },
    {
      "open": 176.26,
      "high": 176.27,
      "low": 176.26,
      "close": 176.26,
      "volume": 2174,
      "datetime": 1640307360000
    },
    {
      "open": 176.26,
      "high": 176.31,
      "low": 176.26,
      "close": 176.3,
      "volume": 15401,
      "datetime": 1640307420000
    },
    {
      "open": 176.3,
      "high": 176.3,
      "low": 176.3,
      "close": 176.3,
      "volume": 1700,
      "datetime": 1640307480000
    },
    {
      "open": 176.3,
      "high": 176.5,
      "low": 176.3,
      "close": 176.32,
      "volume": 5941,
      "datetime": 1640307540000
    }
  ]
})";

std::string mockGetPriceHistoryResp =
    R"({
  "candles": [
    {
      "open": 515.77,
      "high": 520.62,
      "low": 515.08,
      "close": 520.48,
      "volume": 69594574,
      "datetime": 1710910800000
    },
    {
      "open": 523.39,
      "high": 524.11,
      "low": 521.91,
      "close": 522.2,
      "volume": 60256112,
      "datetime": 1710997200000
    },
    {
      "open": 522.11,
      "high": 522.605,
      "low": 520.97,
      "close": 521.21,
      "volume": 79070842,
      "datetime": 1711083600000
    },
    {
      "open": 519.8,
      "high": 520.95,
      "low": 519.61,
      "close": 519.77,
      "volume": 48512108,
      "datetime": 1711342800000
    },
    {
      "open": 521.23,
      "high": 521.58,
      "low": 518.4,
      "close": 518.81,
      "volume": 65463744,
      "datetime": 1711429200000
    },
    {
      "open": 521.71,
      "high": 523.21,
      "low": 519.485,
      "close": 523.17,
      "volume": 82999777,
      "datetime": 1711515600000
    },
    {
      "open": 523.21,
      "high": 524.61,
      "low": 522.78,
      "close": 523.07,
      "volume": 96294886,
      "datetime": 1711602000000
    }
  ],
  "previousClose": 512.86,
  "previousCloseDate": 1710738000000,
  "symbol": "SPY",
  "empty": false
    })";

std::string exampleOptionsChain =
    R"({
  "symbol": "string",
  "status": "string",
  "underlying": {
    "ask": 0,
    "askSize": 0,
    "bid": 0,
    "bidSize": 0,
    "change": 0,
    "close": 0,
    "delayed": true,
    "description": "string",
    "exchangeName": "IND",
    "fiftyTwoWeekHigh": 0,
    "fiftyTwoWeekLow": 0,
    "highPrice": 0,
    "last": 0,
    "lowPrice": 0,
    "mark": 0,
    "markChange": 0,
    "markPercentChange": 0,
    "openPrice": 0,
    "percentChange": 0,
    "quoteTime": 0,
    "symbol": "string",
    "totalVolume": 0,
    "tradeTime": 0
  },
  "strategy": "SINGLE",
  "interval": 0,
  "isDelayed": true,
  "isIndex": true,
  "daysToExpiration": 0,
  "interestRate": 0,
  "underlyingPrice": 0,
  "volatility": 0,
  "callExpDateMap": {
    "additionalProp1": {
      "additionalProp1": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp2": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp3": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      }
    },
    "additionalProp2": {
      "additionalProp1": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp2": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp3": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      }
    },
    "additionalProp3": {
      "additionalProp1": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp2": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp3": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      }
    }
  },
  "putExpDateMap": {
    "additionalProp1": {
      "additionalProp1": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp2": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp3": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      }
    },
    "additionalProp2": {
      "additionalProp1": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp2": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp3": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      }
    },
    "additionalProp3": {
      "additionalProp1": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp2": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp3": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      }
    }
  }
})";

std::string expirationListExample =
    R"({
  "expirationList": [
    {
      "expirationDate": "2022-01-07",
      "daysToExpiration": 2,
      "expirationType": "W",
      "standard": true
    },
    {
      "expirationDate": "2022-01-14",
      "daysToExpiration": 9,
      "expirationType": "W",
      "standard": true
    },
    {
      "expirationDate": "2022-01-21",
      "daysToExpiration": 16,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2022-01-28",
      "daysToExpiration": 23,
      "expirationType": "W",
      "standard": true
    },
    {
      "expirationDate": "2022-02-04",
      "daysToExpiration": 30,
      "expirationType": "W",
      "standard": true
    },
    {
      "expirationDate": "2022-02-11",
      "daysToExpiration": 37,
      "expirationType": "W",
      "standard": true
    },
    {
      "expirationDate": "2022-02-18",
      "daysToExpiration": 44,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2022-03-18",
      "daysToExpiration": 72,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2022-04-14",
      "daysToExpiration": 99,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2022-05-20",
      "daysToExpiration": 135,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2022-06-17",
      "daysToExpiration": 163,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2022-07-15",
      "daysToExpiration": 191,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2022-09-16",
      "daysToExpiration": 254,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2023-01-20",
      "daysToExpiration": 380,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2023-03-17",
      "daysToExpiration": 436,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2023-06-16",
      "daysToExpiration": 527,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2023-09-15",
      "daysToExpiration": 618,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2024-01-19",
      "daysToExpiration": 744,
      "expirationType": "S",
      "standard": true
    }
  ]
})";

std::string multiEquityQuotesExample =
    R"({
  "SPY": {
    "assetMainType": "EQUITY",
    "assetSubType": "ETF",
    "quoteType": "NBBO",
    "realtime": true,
    "ssid": 1281357639,
    "symbol": "SPY",
    "quote": {
      "52WeekHigh": 524.61,
      "52WeekLow": 398.68,
      "askMICId": "ARCX",
      "askPrice": 523.07,
      "askSize": 6,
      "askTime": 1711670400440,
      "bidMICId": "ARCX",
      "bidPrice": 522.95,
      "bidSize": 35,
      "bidTime": 1711670400037,
      "closePrice": 523.17,
      "highPrice": 524.61,
      "lastMICId": "ARCX",
      "lastPrice": 523.07,
      "lastSize": 2528101,
      "lowPrice": 522.78,
      "mark": 523.07,
      "markChange": -0.1,
      "markPercentChange": -0.01911425,
      "netChange": -0.1,
      "netPercentChange": -0.01911425,
      "openPrice": 523.21,
      "postMarketChange": 0,
      "postMarketPercentChange": 0,
      "quoteTime": 1711670400440,
      "securityStatus": "Normal",
      "totalVolume": 96294886,
      "tradeTime": 1711670400075
    },
    "reference": {
      "cusip": "78462F103",
      "description": "SPDR S&P 500 ETF",
      "exchange": "P",
      "exchangeName": "NYSE Arca",
      "isHardToBorrow": false,
      "isShortable": true,
      "htbRate": 0
    }
  },
  "AAPL": {
    "assetMainType": "EQUITY",
    "assetSubType": "COE",
    "quoteType": "NBBO",
    "realtime": true,
    "ssid": 1973757747,
    "symbol": "AAPL",
    "quote": {
      "52WeekHigh": 199.62,
      "52WeekLow": 159.35,
      "askMICId": "ARCX",
      "askPrice": 171.22,
      "askSize": 8,
      "askTime": 1711670396062,
      "bidMICId": "ARCX",
      "bidPrice": 171.2,
      "bidSize": 1,
      "bidTime": 1711670396062,
      "closePrice": 173.31,
      "highPrice": 172.23,
      "lastMICId": "ARCX",
      "lastPrice": 171.21,
      "lastSize": 9,
      "lowPrice": 170.51,
      "mark": 171.48,
      "markChange": -1.83,
      "markPercentChange": -1.05591137,
      "netChange": -2.1,
      "netPercentChange": -1.21170158,
      "openPrice": 171.75,
      "postMarketChange": -0.27,
      "postMarketPercentChange": -0.15745276,
      "quoteTime": 1711670396062,
      "securityStatus": "Normal",
      "totalVolume": 65672690,
      "tradeTime": 1711670399774
    },
    "reference": {
      "cusip": "037833100",
      "description": "Apple Inc",
      "exchange": "Q",
      "exchangeName": "NASDAQ",
      "isHardToBorrow": false,
      "isShortable": true,
      "htbRate": 0
    }
  }
})";