#pragma once

#include <string>

static std::string examplePriceHistory =
    R"({
  "symbol": "AAPL",
  "empty": false,
  "previousClose": 174.56,
  "previousCloseDate": 1639029600000,
  "candles": [
    {
      "open": 175.01,
      "high": 175.15,
      "low": 175.01,
      "close": 175.04,
      "volume": 10719,
      "datetime": 1639137600000
    },
    {
      "open": 175.08,
      "high": 175.09,
      "low": 175.05,
      "close": 175.05,
      "volume": 500,
      "datetime": 1639137660000
    },
    {
      "open": 176.22,
      "high": 176.27,
      "low": 176.22,
      "close": 176.25,
      "volume": 3395,
      "datetime": 1640307300000
    },
    {
      "open": 176.26,
      "high": 176.27,
      "low": 176.26,
      "close": 176.26,
      "volume": 2174,
      "datetime": 1640307360000
    },
    {
      "open": 176.26,
      "high": 176.31,
      "low": 176.26,
      "close": 176.3,
      "volume": 15401,
      "datetime": 1640307420000
    },
    {
      "open": 176.3,
      "high": 176.3,
      "low": 176.3,
      "close": 176.3,
      "volume": 1700,
      "datetime": 1640307480000
    },
    {
      "open": 176.3,
      "high": 176.5,
      "low": 176.3,
      "close": 176.32,
      "volume": 5941,
      "datetime": 1640307540000
    }
  ]
})";

static std::string mockGetPriceHistoryResp =
    R"({
  "candles": [
    {
      "open": 515.77,
      "high": 520.62,
      "low": 515.08,
      "close": 520.48,
      "volume": 69594574,
      "datetime": 1710910800000
    },
    {
      "open": 523.39,
      "high": 524.11,
      "low": 521.91,
      "close": 522.2,
      "volume": 60256112,
      "datetime": 1710997200000
    },
    {
      "open": 522.11,
      "high": 522.605,
      "low": 520.97,
      "close": 521.21,
      "volume": 79070842,
      "datetime": 1711083600000
    },
    {
      "open": 519.8,
      "high": 520.95,
      "low": 519.61,
      "close": 519.77,
      "volume": 48512108,
      "datetime": 1711342800000
    },
    {
      "open": 521.23,
      "high": 521.58,
      "low": 518.4,
      "close": 518.81,
      "volume": 65463744,
      "datetime": 1711429200000
    },
    {
      "open": 521.71,
      "high": 523.21,
      "low": 519.485,
      "close": 523.17,
      "volume": 82999777,
      "datetime": 1711515600000
    },
    {
      "open": 523.21,
      "high": 524.61,
      "low": 522.78,
      "close": 523.07,
      "volume": 96294886,
      "datetime": 1711602000000
    }
  ],
  "previousClose": 512.86,
  "previousCloseDate": 1710738000000,
  "symbol": "SPY",
  "empty": false
    })";

static std::string exampleOptionsChain =
    R"({
  "symbol": "string",
  "status": "string",
  "underlying": {
    "ask": 0,
    "askSize": 0,
    "bid": 0,
    "bidSize": 0,
    "change": 0,
    "close": 0,
    "delayed": true,
    "description": "string",
    "exchangeName": "IND",
    "fiftyTwoWeekHigh": 0,
    "fiftyTwoWeekLow": 0,
    "highPrice": 0,
    "last": 0,
    "lowPrice": 0,
    "mark": 0,
    "markChange": 0,
    "markPercentChange": 0,
    "openPrice": 0,
    "percentChange": 0,
    "quoteTime": 0,
    "symbol": "string",
    "totalVolume": 0,
    "tradeTime": 0
  },
  "strategy": "SINGLE",
  "interval": 0,
  "isDelayed": true,
  "isIndex": true,
  "daysToExpiration": 0,
  "interestRate": 0,
  "underlyingPrice": 0,
  "volatility": 0,
  "callExpDateMap": {
    "additionalProp1": {
      "additionalProp1": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp2": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp3": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      }
    },
    "additionalProp2": {
      "additionalProp1": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp2": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp3": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      }
    },
    "additionalProp3": {
      "additionalProp1": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp2": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp3": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      }
    }
  },
  "putExpDateMap": {
    "additionalProp1": {
      "additionalProp1": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp2": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp3": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      }
    },
    "additionalProp2": {
      "additionalProp1": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp2": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp3": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      }
    },
    "additionalProp3": {
      "additionalProp1": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp2": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      },
      "additionalProp3": {
        "putCall": "PUT",
        "symbol": "string",
        "description": "string",
        "exchangeName": "string",
        "bidPrice": 0,
        "askPrice": 0,
        "lastPrice": 0,
        "markPrice": 0,
        "bidSize": 0,
        "askSize": 0,
        "lastSize": 0,
        "highPrice": 0,
        "lowPrice": 0,
        "openPrice": 0,
        "closePrice": 0,
        "totalVolume": 0,
        "tradeDate": 0,
        "quoteTimeInLong": 0,
        "tradeTimeInLong": 0,
        "netChange": 0,
        "volatility": 0,
        "delta": 0,
        "gamma": 0,
        "theta": 0,
        "vega": 0,
        "rho": 0,
        "timeValue": 0,
        "openInterest": 0,
        "isInTheMoney": true,
        "theoreticalOptionValue": 0,
        "theoreticalVolatility": 0,
        "isMini": true,
        "isNonStandard": true,
        "optionDeliverablesList": [
          {
            "symbol": "string",
            "assetType": "string",
            "deliverableUnits": "string",
            "currencyType": "string"
          }
        ],
        "strikePrice": 0,
        "expirationDate": "string",
        "daysToExpiration": 0,
        "expirationType": "M",
        "lastTradingDay": 0,
        "multiplier": 0,
        "settlementType": "A",
        "deliverableNote": "string",
        "isIndexOption": true,
        "percentChange": 0,
        "markChange": 0,
        "markPercentChange": 0,
        "isPennyPilot": true,
        "intrinsicValue": 0,
        "optionRoot": "string"
      }
    }
  }
})";

static std::string expirationListExample =
    R"({
  "expirationList": [
    {
      "expirationDate": "2022-01-07",
      "daysToExpiration": 2,
      "expirationType": "W",
      "standard": true
    },
    {
      "expirationDate": "2022-01-14",
      "daysToExpiration": 9,
      "expirationType": "W",
      "standard": true
    },
    {
      "expirationDate": "2022-01-21",
      "daysToExpiration": 16,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2022-01-28",
      "daysToExpiration": 23,
      "expirationType": "W",
      "standard": true
    },
    {
      "expirationDate": "2022-02-04",
      "daysToExpiration": 30,
      "expirationType": "W",
      "standard": true
    },
    {
      "expirationDate": "2022-02-11",
      "daysToExpiration": 37,
      "expirationType": "W",
      "standard": true
    },
    {
      "expirationDate": "2022-02-18",
      "daysToExpiration": 44,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2022-03-18",
      "daysToExpiration": 72,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2022-04-14",
      "daysToExpiration": 99,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2022-05-20",
      "daysToExpiration": 135,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2022-06-17",
      "daysToExpiration": 163,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2022-07-15",
      "daysToExpiration": 191,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2022-09-16",
      "daysToExpiration": 254,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2023-01-20",
      "daysToExpiration": 380,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2023-03-17",
      "daysToExpiration": 436,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2023-06-16",
      "daysToExpiration": 527,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2023-09-15",
      "daysToExpiration": 618,
      "expirationType": "S",
      "standard": true
    },
    {
      "expirationDate": "2024-01-19",
      "daysToExpiration": 744,
      "expirationType": "S",
      "standard": true
    }
  ]
})";

static std::string multiEquityQuotesExample =
    R"({
  "AAPL": {
    "assetMainType": "EQUITY",
    "assetSubType": "COE",
    "quoteType": "NBBO",
    "realtime": true,
    "ssid": 1973757747,
    "symbol": "AAPL",
    "quote": {
      "52WeekHigh": 199.62,
      "52WeekLow": 159.78,
      "askMICId": "ARCX",
      "askPrice": 170.17,
      "askSize": 30,
      "askTime": 1712188792415,
      "bidMICId": "XNAS",
      "bidPrice": 170.11,
      "bidSize": 3,
      "bidTime": 1712188793075,
      "closePrice": 168.84,
      "highPrice": 170.68,
      "lastMICId": "XADF",
      "lastPrice": 170.14,
      "lastSize": 1,
      "lowPrice": 168.58,
      "mark": 170.11,
      "markChange": 1.27,
      "markPercentChange": 0.75219142,
      "netChange": 1.3,
      "netPercentChange": 0.76995973,
      "openPrice": 168.79,
      "postMarketChange": 0.49,
      "postMarketPercentChange": 0.28882994,
      "quoteTime": 1712188793075,
      "securityStatus": "Normal",
      "totalVolume": 47691715,
      "tradeTime": 1712188798920
    }
  },
  "CAVA": {
    "assetMainType": "EQUITY",
    "assetSubType": "COE",
    "quoteType": "NBBO",
    "realtime": true,
    "ssid": 90287957,
    "symbol": "CAVA",
    "quote": {
      "52WeekHigh": 71.6,
      "52WeekLow": 29.05,
      "askMICId": "ARCX",
      "askPrice": 67.7,
      "askSize": 4,
      "askTime": 1712186933826,
      "bidMICId": "ARCX",
      "bidPrice": 66.8,
      "bidSize": 5,
      "bidTime": 1712188085815,
      "closePrice": 65.75,
      "highPrice": 67.32,
      "lastPrice": 66.99,
      "lastSize": 21,
      "lowPrice": 63.83,
      "mark": 66.8,
      "markChange": 1.05,
      "markPercentChange": 1.59695817,
      "netChange": 1.24,
      "netPercentChange": 1.88593156,
      "openPrice": 65.38,
      "postMarketChange": 0.22,
      "postMarketPercentChange": 0.32948929,
      "quoteTime": 1712188085815,
      "securityStatus": "Normal",
      "totalVolume": 2769056,
      "tradeTime": 1712188751460
    }
  },
  "MSFT": {
    "assetMainType": "EQUITY",
    "assetSubType": "COE",
    "quoteType": "NBBO",
    "realtime": true,
    "ssid": 1688643765,
    "symbol": "MSFT",
    "quote": {
      "52WeekHigh": 430.82,
      "52WeekLow": 275.37,
      "askMICId": "ARCX",
      "askPrice": 422.5,
      "askSize": 4,
      "askTime": 1712188762434,
      "bidMICId": "ARCX",
      "bidPrice": 422.21,
      "bidSize": 1,
      "bidTime": 1712188762434,
      "closePrice": 421.44,
      "highPrice": 423.26,
      "lastMICId": "XADF",
      "lastPrice": 422.355,
      "lastSize": 1,
      "lowPrice": 419.085,
      "mark": 422.21,
      "markChange": 0.77,
      "markPercentChange": 0.18270691,
      "netChange": 0.915,
      "netPercentChange": 0.21711276,
      "openPrice": 419.73,
      "postMarketChange": 1.905,
      "postMarketPercentChange": 0.45308598,
      "quoteTime": 1712188762434,
      "securityStatus": "Normal",
      "totalVolume": 16502264,
      "tradeTime": 1712188799317
    }
  },
  "QQQ": {
    "assetMainType": "EQUITY",
    "assetSubType": "ETF",
    "quoteType": "NBBO",
    "realtime": true,
    "ssid": 48644470,
    "symbol": "QQQ",
    "quote": {
      "52WeekHigh": 449.34,
      "52WeekLow": 309.89,
      "askMICId": "EDGX",
      "askPrice": 443.86,
      "askSize": 6,
      "askTime": 1712188799756,
      "bidMICId": "EDGX",
      "bidPrice": 443.8,
      "bidSize": 6,
      "bidTime": 1712188799015,
      "closePrice": 441.11,
      "highPrice": 444,
      "lastMICId": "XNAS",
      "lastPrice": 443.82,
      "lastSize": 96,
      "lowPrice": 438.95,
      "mark": 443.8,
      "markChange": 2.69,
      "markPercentChange": 0.60982521,
      "netChange": 2.71,
      "netPercentChange": 0.61435923,
      "openPrice": 438.96,
      "postMarketChange": 1.72,
      "postMarketPercentChange": 0.38905225,
      "quoteTime": 1712188799756,
      "securityStatus": "Normal",
      "totalVolume": 39949750,
      "tradeTime": 1712188799756
    }
  },
  "SPY": {
    "assetMainType": "EQUITY",
    "assetSubType": "ETF",
    "quoteType": "NBBO",
    "realtime": true,
    "ssid": 1281357639,
    "symbol": "SPY",
    "quote": {
      "52WeekHigh": 524.61,
      "52WeekLow": 403.74,
      "askMICId": "ARCX",
      "askPrice": 520.74,
      "askSize": 5,
      "askTime": 1712188800043,
      "bidMICId": "XCIS",
      "bidPrice": 520.66,
      "bidSize": 3,
      "bidTime": 1712188800043,
      "closePrice": 518.84,
      "highPrice": 520.95,
      "lastMICId": "ARCX",
      "lastPrice": 519.41,
      "lastSize": 833829,
      "lowPrice": 517.665,
      "mark": 520.66,
      "markChange": 1.82,
      "markPercentChange": 0.35078251,
      "netChange": 0.57,
      "netPercentChange": 0.10986046,
      "openPrice": 517.72,
      "postMarketChange": 0,
      "postMarketPercentChange": 0,
      "quoteTime": 1712188800043,
      "securityStatus": "Normal",
      "totalVolume": 59155759,
      "tradeTime": 1712188800004
    }
  }
})";